import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes';
import { Hind, Inter} from "next/font/google";
import "@/shared/styles/globals.css";
import Providers from "@/shared/utils/Providers";

const hind = Inter({ subsets: ["latin"], weight:["300" , "400" , "500" , "600" , "700"] });

export const metadata: Metadata = {
  title: "SubsAlert",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      baseTheme: dark
    }}>
    <html lang="en">
       <body className={hind.className}>
        <Providers>
            {children}
        </Providers>
       </body>
    </html>
    </ClerkProvider>
  );
}
