import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs'
import { Inter, Poppins } from "next/font/google";
import "@/shared/styles/globals.css";
import Providers from "@/shared/utils/Providers";

const poppins = Poppins({ subsets: ["latin"], weight:["300" , "400" , "500" , "600" , "700"] });

export const metadata: Metadata = {
  title: "SubsAlert",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
       <body className={poppins.className}>
        <Providers>
            {children}
        </Providers>
       </body>
    </html>
    </ClerkProvider>
  );
}
